[package]
name = "znaky"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
num = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
toml = "0.8.19"
